import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Frontend Solidity Compiler
        </h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Source Code</h2>
            <textarea rows={30} cols={40}>

            </textarea>
            <div className={styles.buttonWrapper}>
              <button>Compile</button>
            </div>
          </div>
          <div className={styles.card}>
            <h2>Compiled ByteCode</h2>
            <textarea readOnly rows={30} cols={40}>

            </textarea>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
